language: python
dist: bionic

notifications:
      email: false

python:
    - "3.5"
    - "3.6"
    - "3.7"
    - "3.8"

install:
    - sudo apt update
    - sudo apt install graphviz libgraphviz-dev

script:
    - pip install .
    - cd test
    - pip install -r requirements.txt
    - if [[ $TRAVIS_PYTHON_VERSION == '3.7' ]]; then pip install black; black --check . ../graphviz2drawio; fi
    - pytest --cov=graphviz2drawio -v test_graphs.py

after_success:
    -  if [[ $TRAVIS_PYTHON_VERSION == '3.7' ]]; then pip install codecov; codecov; fi
